# Generated by Django 5.0.6 on 2024-07-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appComics', '0001_initial'),
    ]

    operations = [
    ]
