# Generated by Django 5.0.6 on 2024-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appComics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
