# Generated by Django 5.0.6 on 2024-07-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appComics', '0002_usuariocomic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
