# Generated by Django 5.0.6 on 2024-07-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appComics', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('forma_pago', models.CharField(choices=[('EF', 'Efectivo'), ('DE', 'Débito'), ('CR', 'Crédito'), ('TR', 'Transferencia')], default='EF', max_length=2)),
            ],
        ),
    ]
